on: [push]

name: CI

jobs:
  build_and_test:
    name: lineup-CI
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: install nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - name: test
        uses: actions-rs/cargo@v1
        with:
          command: test
